### ISSUE TITLE
Create Discord plugin

### ISSUE THREAD

**Issue by mashton** [metagov/gateway#93]
some considerations:
* Consider using discord.py for websockets https://github.com/Rapptz/discord.py
* Implement the actions/events necessary to support "governing" mic muting, video/screenshare
* Add an emoji-voting governance process
* Implement auth endpoints for installation and user login
* Implement all necessary action/events to reach parity with current PolicyKit Discord integrator, then migrate it

**Comment by mashton** [comment]
@shaunagm I already have a working Discord plugin on a branch so I'll create a PR to merge it in, even though PolciyKit won't use it (yet)

**Comment by shaunagm** [comment]
Sounds good. Remind me why PK won't use it?

**Comment by mashton** [comment]
Because the PK Discord integrator uses websockets to listen for actions so it can "govern" them, while this Discord Plugin just uses the interaction api, so it can't "listen" to events on platform-- it can only respond to users interacting directly with the bot.

The PK integrator doesn't really work, tohugh, because the socket is not deployed correctly so it just closes after some time. But there was hesitation to switch over to this gateway discord plugin because it would be losing functionality (you can no longer "govern" message posts, since you cant listen for all messages)

**Comment by mashton** [comment]
Closed with https://github.com/metagov/gateway/pull/168

Follow-up to implement identity linking, https://github.com/metagov/gateway/issues/171
